name: build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: check out code
      uses: actions/checkout@v3

    - name: install dependencies
      run: npm install --include=dev

    - name: lint code
      run: npm run lint

    - name: build code
      run: npm run build

    - name: test code
      run: npm run test